source 'https://rubygems.org'
gem 'sinatra', '1.3.4'
gem 'sinatra-flash', '0.3.0', require: 'sinatra/flash'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'warden', '1.2.1'
gem 'shotgun'
